### ISSUE TITLE
Updating backlinks for renaming

### ISSUE THREAD

**Issue by clehner** [json-ld/rdf-dataset-canonicalization#23]
The repos/resources listed below link(ed) to this specification at its old name and location which is currently a 404.

**Old**: RDF Dataset Normalization <http://json-ld.github.io/normalization/spec/>
**Current**: RDF Dataset Canonicalization <https://json-ld.github.io/rdf-dataset-canonicalization/spec/>

More info: https://github.com/json-ld/rdf-dataset-canonicalization/commit/0522d97b3d60af85f270e78be7166cece4959091, https://github.com/json-ld/rdf-dataset-canonicalization/pull/20

## Active references

These projects and/or specifications are actively linking to the old URL, or where the checkbox is ticked, have fixed their link already. Relevant PRs or issues are linked where existing.

- [ ] https://github.com/w3c-ccg/ld-proofs
- [ ] https://github.com/w3c-ccg/ldp-bbs2020
- [x] https://github.com/w3c-ccg/lds-ecdsa-secp256k1-2019: https://github.com/w3c-ccg/lds-ecdsa-secp256k1-2019/pull/6
- [ ] https://github.com/w3c-ccg/lds-ed25519-2018: https://github.com/w3c-ccg/lds-ed25519-2018/pull/8
- [ ] https://github.com/w3c-ccg/lds-ed25519-2020
- [ ] https://github.com/w3c-ccg/lds-jws2020
- [ ] https://github.com/w3c-ccg/lds-koblitz2016
- [ ] https://github.com/w3c-ccg/lds-merkle-proof-2019
- [ ] https://github.com/w3c-ccg/lds-merkleproof2017
- [ ] https://github.com/w3c-ccg/lds-pseudonymous2016
- [ ] https://github.com/w3c-ccg/lds-redaction2016
- [ ] https://github.com/w3c-ccg/lds-rsa2016
- [ ] https://github.com/w3c-ccg/w3c-ccg.github.io
- [ ] https://github.com/json-ld/json-ld.org: https://github.com/json-ld/json-ld.org/pull/755
- [ ] https://github.com/digitalbazaar/jsonld.js
- [ ] https://github.com/digitalbazaar/php-json-ld
- [ ] https://github.com/digitalbazaar/pyld
- [ ] https://github.com/transmute-industries/respec-github-pages
- [ ] https://github.com/OR13/lds-blockchain2021
- [ ] https://github.com/OR13/lds-pgp2021
- [ ] https://github.com/decentralized-identity/vc-spec-map
- [ ] https://github.com/decentralized-identity/JcsEd25519Signature2020
- [ ] https://github.com/decentralized-identity/OpenPgpSignature2019
- [ ] https://github.com/decentralized-identity/vc-spec-map
- [ ] https://github.com/decentralized-identity/github-did

## Inactive references

References exist here only in historical documents (publication snapshots, minutes, archived repos), and/or in an unused form that does not appear in the the rendered document, or for other reasons are not expected to be updated.

- https://github.com/w3c/json-ld-wg (minutes)
- https://github.com/w3c/webpayments-ig (archived)
- https://github.com/w3c/vc-imp-guide (unused reference)
- https://github.com/w3c/vc-data-model (unused reference)
- https://github.com/w3c/did-core/ (unused reference)
- https://github.com/w3c/did-cbor-note/ (unused reference)
- https://github.com/w3c/vc-use-cases (publication-snapshots)
- https://github.com/w3c-ccg/credential-handler-api (unused reference)
- https://github.com/w3c-ccg/did-method-key (unused reference)
- https://github.com/w3c-ccg/did-method-v1 (unused reference)
- https://github.com/w3c-ccg/did-spec (archived)
- https://github.com/w3c-ccg/didm-btcr (unused reference)
- https://github.com/w3c-ccg/lds-rsa2018 (archived)
- https://github.com/w3c-ccg/traceability-interop (unused reference)
- https://github.com/w3c-ccg/traceability-vocab (unused reference)
- https://github.com/w3c-ccg/vc-http-api (unused reference)
- https://github.com/w3c-ccg/meetings (minutes)
- https://github.com/OR13/traceability-api (unused reference)
- https://github.com/transmute-industries/authorization-credentials (unused reference)
- https://github.com/decentralized-identity/confidential-storage (unused reference)

## Orgs/users searched

W3C (CCG, VCWG, DID WG, JSON-LD CG), and users/orgs linked from [w3id.org/security](https://github.com/perma-id/w3id.org/blob/master/security/.htaccess) (Digital Bazaar, Transmute, DIF, Orie)

- @w3c https://github.com/search?q=org:w3c+normalization/spec&type=code
- @w3c-ccg https://github.com/search?q=org:w3c-ccg+normalization/spec&type=code
- @json-ld https://github.com/search?q=org:json-ld+normalization/spec&type=code
- @digitalbazaar https://github.com/search?q=org:digitalbazaar+normalization/spec&type=code
- @transmute-industries https://github.com/search?q=org:transmute-industries+normalization/spec&type=code
- @OR13 https://github.com/search?q=user:or13+normalization/spec&type=code
- @decentralized-identity https://github.com/search?q=org:decentralized-identity+normalization/spec&type=code

---

It may be appropriate to close this issue if a redirect from the old URL is implemented (#22), but for now hopefully this issue may be useful.

**Comment by davidlehn** [comment]
Added a redirect page here: https://github.com/json-ld/json-ld.github.io.

Browsers should now redirect https://json-ld.github.io/normalization/spec/ to https://json-ld.github.io/rdf-dataset-canonicalization/spec/.

Hopefully other active pages will update their links over time, but this should help with all the historic references.

**Comment by clehner** [comment]
@davidlehn great, thanks. I think that's good enough to close this issue, unless the maintainers here would prefer otherwise. I don't recall finding links to fragment identifiers (which would not be carried through the HTML-based redirect).
